### ISSUE TITLE
Trojan Detected

### ISSUE THREAD

**Issue by CoopCrediplata** [icflorescu/expose-wsl#9]
Need to install the following packages:
  expose-wsl@1.1.7
Ok to proceed? (y) y
                                                   _
   _____  ___ __   ___  ___  ___     __      _____| |
  / _ \ \/ / '_ \ / _ \/ __|/ _ \____\ \ /\ / / __| |
 |  __/>  <| |_) | (_) \__ \  __/_____\ V  V /\__ \ |
  \___/_/\_\ .__/ \___/|___/\___|      \_/\_/ |___/_|
           |_|

⏳ Downloading WSLHostPatcher... extracting... running... /home/support/.npm/_npx/0e95d415fb20f5d8/node_modules/expose-wsl/WSLHostPatcher.exe: Invalid argument
failed to run ❌
🔥 Please report this issue at https://github.com/icflorescu/expose-wsl/issues
/home/support/.npm/_npx/0e95d415fb20f5d8/node_modules/expose-wsl/WSLHostPatcher.exe: Invalid argument

![Trojan](https://github.com/icflorescu/expose-wsl/assets/134554650/c1f4bc89-973b-4e40-a624-6064bd09d834)

**Comment by enfermero-dev** [comment]
also got this, is the source file infected, cause ive installed this script on another pc and no problem... 
maybe a false positive?

i wont risk it until this issue is answered by dev.

edit: checked the original exe file repo, virus alert could show because of nature of the program:
[https://github.com/CzBiX/WSLHostPatcher/discussions/16](https://github.com/CzBiX/WSLHostPatcher/discussions/16)

**Comment by icflorescu** [comment]
As @CzBiX mentioned, this is to be expected. Afterall, the host patcher is executing some commands that alter the standard WSL behavior. Opening access from remote addresses could lead to security issues, but as a developer you probably know what you're doing.
The code is open-source and therefore publicly available, this project was born out of convenience, but if you have concerns, feel free to use the manual alternatives.
